### ISSUE TITLE
No Sensors Visible

### ISSUE THREAD

**Issue by noddy119** [Seeed-Solution/SenseCraft-HomeAssistant#2]
Hi  I configure the integration with username and password, select global server I get to select my T1000 sensor but it never shows any devices or entities.  I can view the device in my sensecap.seeed.cc account ok

There is an error in my log:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 19:50:21 (1 occurrences)
Last logged: 19:50:21

Error while setting up sensecraft platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sensecraft/sensor.py", line 77, in async_setup_entry
    entities.append(CloudSensor(deviceInfo))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sensecraft/sensor.py", line 171, in __init__
    measurementInfo = MEASUREMENT_DICT[self._measurementID]
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: '5003'

**Comment by chenwenhao568** [comment]
5003 measurements have been added, and default values ​​for no measurements have been added
